// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: internal/protobuf/resticky.proto

package resticky

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestickyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timeout     string `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *RestickyRequest) Reset() {
	*x = RestickyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_resticky_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestickyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestickyRequest) ProtoMessage() {}

func (x *RestickyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_resticky_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestickyRequest.ProtoReflect.Descriptor instead.
func (*RestickyRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_resticky_proto_rawDescGZIP(), []int{0}
}

func (x *RestickyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestickyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestickyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestickyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RestickyRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type RestickyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RestickyResponse) Reset() {
	*x = RestickyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_resticky_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestickyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestickyResponse) ProtoMessage() {}

func (x *RestickyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_resticky_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestickyResponse.ProtoReflect.Descriptor instead.
func (*RestickyResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_resticky_proto_rawDescGZIP(), []int{1}
}

func (x *RestickyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestickyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RestickyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestickyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_protobuf_resticky_proto protoreflect.FileDescriptor

var file_internal_protobuf_resticky_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x22, 0x89, 0x01, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x66, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x74,
	0x69, 0x63, 0x6b, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x32, 0x9b, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x4c, 0x6f, 0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x12,
	0x19, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x69,
	0x63, 0x6b, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x69, 0x63, 0x6b, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobuf_resticky_proto_rawDescOnce sync.Once
	file_internal_protobuf_resticky_proto_rawDescData = file_internal_protobuf_resticky_proto_rawDesc
)

func file_internal_protobuf_resticky_proto_rawDescGZIP() []byte {
	file_internal_protobuf_resticky_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_resticky_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobuf_resticky_proto_rawDescData)
	})
	return file_internal_protobuf_resticky_proto_rawDescData
}

var file_internal_protobuf_resticky_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protobuf_resticky_proto_goTypes = []interface{}{
	(*RestickyRequest)(nil),  // 0: resticky.RestickyRequest
	(*RestickyResponse)(nil), // 1: resticky.RestickyResponse
}
var file_internal_protobuf_resticky_proto_depIdxs = []int32{
	0, // 0: resticky.RestickyService.LockAll:input_type -> resticky.RestickyRequest
	0, // 1: resticky.RestickyService.UnlockAll:input_type -> resticky.RestickyRequest
	1, // 2: resticky.RestickyService.LockAll:output_type -> resticky.RestickyResponse
	1, // 3: resticky.RestickyService.UnlockAll:output_type -> resticky.RestickyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protobuf_resticky_proto_init() }
func file_internal_protobuf_resticky_proto_init() {
	if File_internal_protobuf_resticky_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protobuf_resticky_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestickyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_resticky_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestickyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobuf_resticky_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_resticky_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_resticky_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_resticky_proto_msgTypes,
	}.Build()
	File_internal_protobuf_resticky_proto = out.File
	file_internal_protobuf_resticky_proto_rawDesc = nil
	file_internal_protobuf_resticky_proto_goTypes = nil
	file_internal_protobuf_resticky_proto_depIdxs = nil
}
