// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/osousa/resticky/internal"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg internal.ServerConfig, cnn internal.ConnManagerConfig) (*App, error) {
	logger, err := internal.ProvideZap()
	if err != nil {
		return nil, err
	}
	connManager, err := internal.ProvideConnManager(ctx, cnn, logger)
	if err != nil {
		return nil, err
	}
	server := internal.ProvideServer(cfg, logger, connManager)
	app := ProvideApp(ctx, logger, server)
	return app, nil
}

// wire.go:

var appSet = wire.NewSet(
	ProvideApp,
)

var commonSet = wire.NewSet(internal.ProvideConnManager, internal.ProvideServer, internal.ProvideZap)

var megaSet = wire.NewSet(
	commonSet,
	appSet,
)
